// Code generated by generate-datasources; DO NOT EDIT.

package network

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lxc/terraform-provider-incus/internal/common"
	"github.com/lxc/terraform-provider-incus/internal/errors"
	provider_config "github.com/lxc/terraform-provider-incus/internal/provider-config"
)

type NetworkPeerDataSourceModel struct {
	Name    types.String `tfsdk:"name"`
	Network types.String `tfsdk:"network"`
	Project types.String `tfsdk:"project"`
	Target  types.String `tfsdk:"target"`
	Remote  types.String `tfsdk:"remote"`

	Description types.String `tfsdk:"description"`
	Config      types.Map    `tfsdk:"config"`
	Status      types.String `tfsdk:"status"`

	// Extra attributes.
	TargetProject     types.String `tfsdk:"target_project"`
	TargetNetwork     types.String `tfsdk:"target_network"`
	TargetIntegration types.String `tfsdk:"target_integration"`
	Type              types.String `tfsdk:"type"`
}

type NetworkPeerDataSource struct {
	provider *provider_config.IncusProviderConfig
}

func NewNetworkPeerDataSource() datasource.DataSource {
	return &NetworkPeerDataSource{}
}

func (d *NetworkPeerDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = fmt.Sprintf("%s_network_peer", req.ProviderTypeName)
}

func (d *NetworkPeerDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required: true,
			},

			"network": schema.StringAttribute{
				Required: true,
			},

			"project": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"remote": schema.StringAttribute{
				Optional: true,
			},

			"target": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"config": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},

			"status": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			// Extra attributes.
			"target_project": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"target_network": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"target_integration": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

func (d *NetworkPeerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	data := req.ProviderData
	if data == nil {
		return
	}

	provider, ok := data.(*provider_config.IncusProviderConfig)
	if !ok {
		resp.Diagnostics.Append(errors.NewProviderDataTypeError(req.ProviderData))
		return
	}

	d.provider = provider
}

func (d *NetworkPeerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state NetworkPeerDataSourceModel
	var diags diag.Diagnostics

	diags = req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	providerRemote := state.Remote.ValueString()
	providerProjectName := state.Project.ValueString()
	providerTarget := state.Target.ValueString()
	server, err := d.provider.InstanceServer(providerRemote, providerProjectName, providerTarget)
	if err != nil {
		resp.Diagnostics.Append(errors.NewInstanceServerError(err))
		return
	}
	networkName := state.Network.ValueString()

	networkPeerName := state.Name.ValueString()
	networkPeer, _, err := server.GetNetworkPeer(networkName, networkPeerName)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Failed to retrieve existing network peer %q", networkPeerName), err.Error())
		return
	}

	config, diags := common.ToConfigMapType(ctx, common.ToNullableConfig(networkPeer.Config), state.Config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	state.Name = types.StringValue(networkPeer.Name)
	state.Description = types.StringValue(networkPeer.Description)
	state.Status = types.StringValue(networkPeer.Status)
	state.Config = config

	// Extra attributes.
	state.TargetProject = types.StringValue(networkPeer.TargetProject)
	state.TargetNetwork = types.StringValue(networkPeer.TargetNetwork)
	state.TargetIntegration = types.StringValue(networkPeer.TargetIntegration)
	state.Type = types.StringValue(networkPeer.Type)

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}
