// Code generated by generate-datasources; DO NOT EDIT.

package network

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lxc/terraform-provider-incus/internal/common"
	"github.com/lxc/terraform-provider-incus/internal/errors"
	provider_config "github.com/lxc/terraform-provider-incus/internal/provider-config"
)

type NetworkDataSourceModel struct {
	Name types.String `tfsdk:"name"`

	Project types.String `tfsdk:"project"`
	Target  types.String `tfsdk:"target"`
	Remote  types.String `tfsdk:"remote"`

	Description types.String `tfsdk:"description"`
	Config      types.Map    `tfsdk:"config"`
	Status      types.String `tfsdk:"status"`
	Locations   types.List   `tfsdk:"locations"`

	// Extra attributes.
	Type    types.String `tfsdk:"type"`
	Managed types.Bool   `tfsdk:"managed"`
}

type NetworkDataSource struct {
	provider *provider_config.IncusProviderConfig
}

func NewNetworkDataSource() datasource.DataSource {
	return &NetworkDataSource{}
}

func (d *NetworkDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = fmt.Sprintf("%s_network", req.ProviderTypeName)
}

func (d *NetworkDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required: true,
			},

			"project": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"remote": schema.StringAttribute{
				Optional: true,
			},

			"target": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"config": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},

			"status": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"locations": schema.ListAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
			},

			// Extra attributes.
			"type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"managed": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

func (d *NetworkDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	data := req.ProviderData
	if data == nil {
		return
	}

	provider, ok := data.(*provider_config.IncusProviderConfig)
	if !ok {
		resp.Diagnostics.Append(errors.NewProviderDataTypeError(req.ProviderData))
		return
	}

	d.provider = provider
}

func (d *NetworkDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state NetworkDataSourceModel
	var diags diag.Diagnostics

	diags = req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	providerRemote := state.Remote.ValueString()
	providerProjectName := state.Project.ValueString()
	providerTarget := state.Target.ValueString()
	server, err := d.provider.InstanceServer(providerRemote, providerProjectName, providerTarget)
	if err != nil {
		resp.Diagnostics.Append(errors.NewInstanceServerError(err))
		return
	}

	networkName := state.Name.ValueString()
	network, _, err := server.GetNetwork(networkName)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Failed to retrieve existing network %q", networkName), err.Error())
		return
	}

	config, diags := common.ToConfigMapType(ctx, common.ToNullableConfig(network.Config), state.Config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	locations, diags := types.ListValueFrom(ctx, types.StringType, network.Locations)
	resp.Diagnostics.Append(diags...)
	if diags.HasError() {
		return
	}

	state.Name = types.StringValue(network.Name)
	state.Description = types.StringValue(network.Description)
	state.Status = types.StringValue(network.Status)
	state.Locations = locations
	state.Config = config

	// Extra attributes.
	state.Type = types.StringValue(network.Type)
	state.Managed = types.BoolValue(network.Managed)

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}
