// Code generated by generate-datasources; DO NOT EDIT.

package network

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"github.com/lxc/terraform-provider-incus/internal/common"
	"github.com/lxc/terraform-provider-incus/internal/errors"
	provider_config "github.com/lxc/terraform-provider-incus/internal/provider-config"
)

type NetworkForwardDataSourceModel struct {
	ListenAddress types.String `tfsdk:"listen_address"`
	Network       types.String `tfsdk:"network"`
	Project       types.String `tfsdk:"project"`
	Target        types.String `tfsdk:"target"`
	Remote        types.String `tfsdk:"remote"`

	Description types.String `tfsdk:"description"`
	Config      types.Map    `tfsdk:"config"`
	Location    types.String `tfsdk:"location"`

	// Extra attributes.
	Ports types.List `tfsdk:"ports"`
}

type NetworkForwardDataSource struct {
	provider *provider_config.IncusProviderConfig
}

func NewNetworkForwardDataSource() datasource.DataSource {
	return &NetworkForwardDataSource{}
}

func (d *NetworkForwardDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = fmt.Sprintf("%s_network_forward", req.ProviderTypeName)
}

func (d *NetworkForwardDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"listen_address": schema.StringAttribute{
				Required: true,
			},

			"network": schema.StringAttribute{
				Required: true,
			},

			"project": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"remote": schema.StringAttribute{
				Optional: true,
			},

			"target": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"config": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},

			"location": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			// Extra attributes.
			"ports": schema.ListAttribute{
				Optional: true,
				Computed: true,
				ElementType: types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"description":    types.StringType,
						"protocol":       types.StringType,
						"listen_port":    types.StringType,
						"target_port":    types.StringType,
						"target_address": types.StringType,
						"snat":           types.BoolType,
					},
				},
			},
		},
	}
}

func (d *NetworkForwardDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	data := req.ProviderData
	if data == nil {
		return
	}

	provider, ok := data.(*provider_config.IncusProviderConfig)
	if !ok {
		resp.Diagnostics.Append(errors.NewProviderDataTypeError(req.ProviderData))
		return
	}

	d.provider = provider
}

func (d *NetworkForwardDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state NetworkForwardDataSourceModel
	var diags diag.Diagnostics

	diags = req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	providerRemote := state.Remote.ValueString()
	providerProjectName := state.Project.ValueString()
	providerTarget := state.Target.ValueString()
	server, err := d.provider.InstanceServer(providerRemote, providerProjectName, providerTarget)
	if err != nil {
		resp.Diagnostics.Append(errors.NewInstanceServerError(err))
		return
	}
	networkName := state.Network.ValueString()

	networkForwardName := state.ListenAddress.ValueString()
	networkForward, _, err := server.GetNetworkForward(networkName, networkForwardName)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Failed to retrieve existing network forward %q", networkForwardName), err.Error())
		return
	}

	config, diags := common.ToConfigMapType(ctx, common.ToNullableConfig(networkForward.Config), state.Config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	state.ListenAddress = types.StringValue(networkForward.ListenAddress)
	state.Description = types.StringValue(networkForward.Description)
	state.Location = types.StringValue(networkForward.Location)
	state.Config = config

	// Extra attributes.
	state.Ports, diags = toNetworkForwardPortsListTypeValue(ctx, networkForward.Ports)
	resp.Diagnostics.Append(diags...)
	if diags.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func getNetworkForwardPortsListType() types.ListType {
	return types.ListType{
		ElemType: types.MapType{
			ElemType: types.ObjectType{
				AttrTypes: map[string]attr.Type{
					"description":    types.StringType,
					"protocol":       types.StringType,
					"listen_port":    types.StringType,
					"target_port":    types.StringType,
					"target_address": types.StringType,
					"snat":           types.BoolType,
				},
			},
		},
	}
}

func toNetworkForwardPortsListTypeValue(ctx context.Context, in any) (types.List, diag.Diagnostics) {
	networkforwardPortsListType := getNetworkForwardPortsListType()
	nilList := types.ListNull(networkforwardPortsListType)

	networkforwardPortsItems, err := common.ToMapStringAnySlice(in)
	if err != nil {
		return nilList, diag.Diagnostics{diag.NewErrorDiagnostic("to slice of maps conversion failed", err.Error())}
	}

	networkforwardPortsList := make([]attr.Value, 0, len(networkforwardPortsItems))
	for _, networkforwardPortsItem := range networkforwardPortsItems {
		objectValue, diags := toNetworkForwardPortsObjectTypeValue(ctx, networkforwardPortsItem)
		if diags.HasError() {
			return nilList, diags
		}

		networkforwardPortsList = append(networkforwardPortsList, objectValue)
	}

	return types.ListValue(networkforwardPortsListType, networkforwardPortsList)
}

func getNetworkForwardPortsObjectType() types.ObjectType {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"description":    types.StringType,
			"protocol":       types.StringType,
			"listen_port":    types.StringType,
			"target_port":    types.StringType,
			"target_address": types.StringType,
			"snat":           types.BoolType,
		},
	}
}

func toNetworkForwardPortsObjectTypeValue(ctx context.Context, in map[string]any) (obj basetypes.ObjectValue, diags diag.Diagnostics) {
	networkforwardPortsObjectType := getNetworkForwardPortsObjectType()
	nilObject := types.ObjectNull(networkforwardPortsObjectType.AttrTypes)

	res := map[string]attr.Value{}
	descriptionStringValue := types.StringNull()
	descriptionAny, ok := in["description"]
	if ok {
		descriptionString, ok := descriptionAny.(string)
		if ok {
			descriptionStringValue = types.StringValue(descriptionString)
		}
	}
	res["description"] = descriptionStringValue

	protocolStringValue := types.StringNull()
	protocolAny, ok := in["protocol"]
	if ok {
		protocolString, ok := protocolAny.(string)
		if ok {
			protocolStringValue = types.StringValue(protocolString)
		}
	}
	res["protocol"] = protocolStringValue

	listenPortStringValue := types.StringNull()
	listenPortAny, ok := in["listen_port"]
	if ok {
		listenPortString, ok := listenPortAny.(string)
		if ok {
			listenPortStringValue = types.StringValue(listenPortString)
		}
	}
	res["listen_port"] = listenPortStringValue

	targetPortStringValue := types.StringNull()
	targetPortAny, ok := in["target_port"]
	if ok {
		targetPortString, ok := targetPortAny.(string)
		if ok {
			targetPortStringValue = types.StringValue(targetPortString)
		}
	}
	res["target_port"] = targetPortStringValue

	targetAddressStringValue := types.StringNull()
	targetAddressAny, ok := in["target_address"]
	if ok {
		targetAddressString, ok := targetAddressAny.(string)
		if ok {
			targetAddressStringValue = types.StringValue(targetAddressString)
		}
	}
	res["target_address"] = targetAddressStringValue

	snatBoolValue := types.BoolNull()
	snatAny, ok := in["snat"]
	if ok {
		snatBool, ok := snatAny.(bool)
		if ok {
			snatBoolValue = types.BoolValue(snatBool)
		}
	}
	res["snat"] = snatBoolValue

	obj, diags = types.ObjectValue(networkforwardPortsObjectType.AttrTypes, res)
	if diags.HasError() {
		return nilObject, diags
	}

	return obj, nil
}
