// Code generated by generate-datasources; DO NOT EDIT.

package instance

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lxc/terraform-provider-incus/internal/common"
	"github.com/lxc/terraform-provider-incus/internal/errors"
	provider_config "github.com/lxc/terraform-provider-incus/internal/provider-config"
)

type InstanceDataSourceModel struct {
	Name types.String `tfsdk:"name"`

	Project types.String `tfsdk:"project"`
	Target  types.String `tfsdk:"target"`
	Remote  types.String `tfsdk:"remote"`

	Description types.String `tfsdk:"description"`
	Config      types.Map    `tfsdk:"config"`
	Status      types.String `tfsdk:"status"`
	Location    types.String `tfsdk:"location"`

	// Extra attributes.
	Devices      types.Set    `tfsdk:"device"`
	Type         types.String `tfsdk:"type"`
	Architecture types.String `tfsdk:"architecture"`
	Ephemeral    types.Bool   `tfsdk:"ephemeral"`
	Profiles     types.List   `tfsdk:"profiles"`
	Stateful     types.Bool   `tfsdk:"stateful"`
}

type InstanceDataSource struct {
	provider *provider_config.IncusProviderConfig
}

func NewInstanceDataSource() datasource.DataSource {
	return &InstanceDataSource{}
}

func (d *InstanceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = fmt.Sprintf("%s_instance", req.ProviderTypeName)
}

func (d *InstanceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required: true,
			},

			"project": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"remote": schema.StringAttribute{
				Optional: true,
			},

			"target": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"config": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},

			"status": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"location": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			// Extra attributes.

			"type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"architecture": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"ephemeral": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},

			"profiles": schema.ListAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
			},

			"stateful": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
		},
		Blocks: map[string]schema.Block{
			"device": schema.SetNestedBlock{
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Computed: true,
						},

						"type": schema.StringAttribute{
							Computed: true,
						},

						"properties": schema.MapAttribute{
							Computed:    true,
							ElementType: types.StringType,
						},
					},
				},
			},
		},
	}
}

func (d *InstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	data := req.ProviderData
	if data == nil {
		return
	}

	provider, ok := data.(*provider_config.IncusProviderConfig)
	if !ok {
		resp.Diagnostics.Append(errors.NewProviderDataTypeError(req.ProviderData))
		return
	}

	d.provider = provider
}

func (d *InstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state InstanceDataSourceModel
	var diags diag.Diagnostics

	diags = req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	providerRemote := state.Remote.ValueString()
	providerProjectName := state.Project.ValueString()
	providerTarget := state.Target.ValueString()
	server, err := d.provider.InstanceServer(providerRemote, providerProjectName, providerTarget)
	if err != nil {
		resp.Diagnostics.Append(errors.NewInstanceServerError(err))
		return
	}

	instanceName := state.Name.ValueString()
	instance, _, err := server.GetInstance(instanceName)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Failed to retrieve existing instance %q", instanceName), err.Error())
		return
	}

	config, diags := common.ToConfigMapType(ctx, common.ToNullableConfig(instance.Config), state.Config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	devices, diags := common.ToDeviceSetType(ctx, instance.Devices)
	resp.Diagnostics.Append(diags...)
	if diags.HasError() {
		return
	}

	state.Devices = devices

	state.Name = types.StringValue(instance.Name)
	state.Description = types.StringValue(instance.Description)
	state.Status = types.StringValue(instance.Status)
	state.Location = types.StringValue(instance.Location)
	state.Config = config

	// Extra attributes.
	state.Type = types.StringValue(instance.Type)
	state.Architecture = types.StringValue(instance.Architecture)
	state.Ephemeral = types.BoolValue(instance.Ephemeral)
	state.Profiles, diags = toInstanceProfilesListTypeValue(ctx, instance.Profiles)
	resp.Diagnostics.Append(diags...)
	if diags.HasError() {
		return
	}
	state.Stateful = types.BoolValue(instance.Stateful)

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func getInstanceProfilesListType() types.ListType {
	return types.ListType{
		ElemType: types.StringType,
	}
}

func toInstanceProfilesListTypeValue(ctx context.Context, in any) (types.List, diag.Diagnostics) {
	return types.ListValueFrom(ctx, types.StringType, in)
}
