// Code generated by generate-datasources; DO NOT EDIT.

package certificate

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lxc/terraform-provider-incus/internal/errors"
	provider_config "github.com/lxc/terraform-provider-incus/internal/provider-config"
)

type CertificateDataSourceModel struct {
	Fingerprint types.String `tfsdk:"fingerprint"`

	Remote types.String `tfsdk:"remote"`

	Description types.String `tfsdk:"description"`

	// Extra attributes.
	Name        types.String `tfsdk:"name"`
	Certificate types.String `tfsdk:"certificate"`
	Type        types.String `tfsdk:"type"`
	Restricted  types.Bool   `tfsdk:"restricted"`
	Projects    types.List   `tfsdk:"projects"`
}

type CertificateDataSource struct {
	provider *provider_config.IncusProviderConfig
}

func NewCertificateDataSource() datasource.DataSource {
	return &CertificateDataSource{}
}

func (d *CertificateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = fmt.Sprintf("%s_certificate", req.ProviderTypeName)
}

func (d *CertificateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"fingerprint": schema.StringAttribute{
				Required: true,
			},

			"remote": schema.StringAttribute{
				Optional: true,
			},

			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			// Extra attributes.
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"certificate": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},

			"restricted": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},

			"projects": schema.ListAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
			},
		},
	}
}

func (d *CertificateDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	data := req.ProviderData
	if data == nil {
		return
	}

	provider, ok := data.(*provider_config.IncusProviderConfig)
	if !ok {
		resp.Diagnostics.Append(errors.NewProviderDataTypeError(req.ProviderData))
		return
	}

	d.provider = provider
}

func (d *CertificateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state CertificateDataSourceModel
	var diags diag.Diagnostics

	diags = req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	providerRemote := state.Remote.ValueString()
	providerProjectName := ""
	providerTarget := ""
	server, err := d.provider.InstanceServer(providerRemote, providerProjectName, providerTarget)
	if err != nil {
		resp.Diagnostics.Append(errors.NewInstanceServerError(err))
		return
	}

	certificateName := state.Fingerprint.ValueString()
	certificate, _, err := server.GetCertificate(certificateName)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Failed to retrieve existing certificate %q", certificateName), err.Error())
		return
	}

	state.Fingerprint = types.StringValue(certificate.Fingerprint)
	state.Description = types.StringValue(certificate.Description)

	// Extra attributes.
	state.Name = types.StringValue(certificate.Name)
	state.Certificate = types.StringValue(certificate.Certificate)
	state.Type = types.StringValue(certificate.Type)
	state.Restricted = types.BoolValue(certificate.Restricted)
	state.Projects, diags = toCertificateProjectsListTypeValue(ctx, certificate.Projects)
	resp.Diagnostics.Append(diags...)
	if diags.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func getCertificateProjectsListType() types.ListType {
	return types.ListType{
		ElemType: types.StringType,
	}
}

func toCertificateProjectsListTypeValue(ctx context.Context, in any) (types.List, diag.Diagnostics) {
	return types.ListValueFrom(ctx, types.StringType, in)
}
