// Code generated by generate-datasources; DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/lxc/terraform-provider-incus/internal/network"
	"github.com/lxc/terraform-provider-incus/internal/profile"
	"github.com/lxc/terraform-provider-incus/internal/project"
	"github.com/lxc/terraform-provider-incus/internal/storage"
)

func generatedDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		network.NewNetworkDataSource,
		network.NewNetworkACLDataSource,
		network.NewNetworkAddressSetDataSource,
		network.NewNetworkForwardDataSource,
		network.NewNetworkIntegrationDataSource,
		network.NewNetworkLoadBalancerDataSource,
		network.NewNetworkPeerDataSource,
		network.NewNetworkZoneDataSource,
		profile.NewProfileDataSource,
		project.NewProjectDataSource,
		storage.NewStorageBucketDataSource,
		storage.NewStoragePoolDataSource,
		storage.NewStorageVolumeDataSource,
	}
}
